### ISSUE TITLE
subject claim missing

### ISSUE THREAD

**Issue by mcentennial** [miroslavpopovic/auth-sample-openiddict#1]
I ran these projects (Auth, WeatherApi, WeatherSummaryApi, and MvcClient), and they worked well for the first time. But the program doesn't work for the second time; after running the program for the second time, the Missing Claim error occurred "The specified principal was rejected because the mandatory subject claim was missing."

![image](https://user-images.githubusercontent.com/112662756/188011739-50864e6f-98eb-4a9b-90b8-63bb121746cf.png)

**Comment by miroslavpopovic** [comment]
Hi @mcentennial,

Thanks for reporting this. I will check as soon as I find some time...

On top of my head, it probably has something to do with the subject (`sub`) claim not being populated by default by OpenIddict. I have been adding it manually in few places, to overcome this issue, but it seems like I missed adding it everywhere.

You can check the code in [`AuthorizationController`](https://github.com/miroslavpopovic/auth-sample-openiddict/blob/main/src/Auth/Controllers/AuthorizationController.cs), in [`Accept`](https://github.com/miroslavpopovic/auth-sample-openiddict/blob/main/src/Auth/Controllers/AuthorizationController.cs#L229) and [`VerifyAccept`](https://github.com/miroslavpopovic/auth-sample-openiddict/blob/main/src/Auth/Controllers/AuthorizationController.cs#L346) methods.

```csharp
// Note: while ASP.NET Core Identity uses the legacy WS-Federation claims (exposed by the ClaimTypes class),
// OpenIddict uses the newer JWT claims defined by the OpenID Connect specification. To ensure the mandatory
// subject claim is correctly populated (and avoid an InvalidOperationException), it's manually added here.
if (string.IsNullOrEmpty(principal.FindFirstValue(Claims.Subject)))
{
    principal.SetClaim(Claims.Subject, userId);
}
```

The hint for this was found in this SO answer by @kevinchalet - https://stackoverflow.com/a/44845552/119230. You can check it for an alternative approach too.

**Comment by miroslavpopovic** [comment]
@etedalii created a pull request with a fix for this (thanks!), so hopefully it should be working OK now 😃
